package com.xzk.tech.block;

import com.xzk.tech.Utils;
import com.xzk.tech.block.SmallBoilers.BoilersBase;
import net.minecraft.block.Block;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class BlockRegistry {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, Utils.MOD_ID);
    public static final RegistryObject<Block> Beryl = BLOCKS.register("beryl", Beryl::new);
    public static final RegistryObject<Block> Spodumene = BLOCKS.register("spodumene", Spodumene::new);
    public static final RegistryObject<Block> Lepidolite = BLOCKS.register("lepidolite", Lepidolite::new);
    public static final RegistryObject<Block> BoraxOre = BLOCKS.register("borax_ore", BoraxOre::new);
    public static final RegistryObject<Block> Priceite = BLOCKS.register("priceite", Priceite::new);
    public static final RegistryObject<Block> RockSaltOre = BLOCKS.register("rock_salt_ore", RockSaltOre::new);
    public static final RegistryObject<Block> Magnesite = BLOCKS.register("magnesite", Magnesite::new);
    public static final RegistryObject<Block> Carnallite = BLOCKS.register("carnallite", Carnallite::new);
    public static final RegistryObject<Block> Bauxite = BLOCKS.register("bauxite", Bauxite::new);
    public static final RegistryObject<Block> Apatite = BLOCKS.register("apatite", Apatite::new);
    public static final RegistryObject<Block> SulfurOre = BLOCKS.register("sulfur_ore", SulfurOre::new);//WIP
    public static final RegistryObject<Block> CalciumCarbonate = BLOCKS.register("calcium_carbonate", CalciumCarbonate::new);
    public static final RegistryObject<Block> Chromite = BLOCKS.register("chromite", Chromite::new);
    public static final RegistryObject<Block> Pyrolusite = BLOCKS.register("pyrolusite", Pyrolusite::new);
    public static final RegistryObject<Block> Psilomelane = BLOCKS.register("psilomelane", Psilomelane::new);
    public static final RegistryObject<Block> Magnetite = BLOCKS.register("magnetite", Magnetite::new);
    public static final RegistryObject<Block> Pentlandite = BLOCKS.register("pentlandite", Pentlandite::new);
    public static final RegistryObject<Block> Chalcocite = BLOCKS.register("chalcocite", Chalcocite::new);
    public static final RegistryObject<Block> Chalcopyrite = BLOCKS.register("chalcopyrite", Chalcopyrite::new);
    public static final RegistryObject<Block> SphaleriteAndGalena = BLOCKS.register("sphalerite_and_galena", SphaleriteAndGalena::new);
    public static final RegistryObject<Block> Smithsonite = BLOCKS.register("smithsonite", Smithsonite::new);
    public static final RegistryObject<Block> Arsenopyrite = BLOCKS.register("arsenopyrite", Arsenopyrite::new);
    public static final RegistryObject<Block> Stibnite = BLOCKS.register("stibnite", Stibnite::new);
    public static final RegistryObject<Block> Cassiterite = BLOCKS.register("cassiterite", Cassiterite::new);
    public static final RegistryObject<Block> Pollucite = BLOCKS.register("pollucite", Pollucite::new);
    public static final RegistryObject<Block> Witherite = BLOCKS.register("witherite", Witherite::new);
    public static final RegistryObject<Block> Barite = BLOCKS.register("barite", Barite::new);
    public static final RegistryObject<Block> Cinnabar = BLOCKS.register("cinnabar", Cinnabar::new);
    public static final RegistryObject<Block> Bismite = BLOCKS.register("bismite", Bismite::new);
    public static final RegistryObject<Block> DeepStone = BLOCKS.register("deep_stone", DeepStone::new);
    public static final RegistryObject<Block> VeryDeepStone = BLOCKS.register("very_deep_stone", VeryDeepStone::new);
    public static final RegistryObject<Block> SpodumeneDeep = BLOCKS.register("spodumene_deep",SpodumeneDeep::new);
    public static final RegistryObject<Block> PolluciteDeep = BLOCKS.register("pollucite_deep",PolluciteDeep::new);
    public static final RegistryObject<Block> LepidoliteDeep = BLOCKS.register("lepidolite_deep",LepidoliteDeep::new);
    public static final RegistryObject<Block> Rutile = BLOCKS.register("rutile",Rutile::new);
    public static final RegistryObject<Block> ZirconProducts = BLOCKS.register("zircon_products",ZirconProducts::new);
    public static final RegistryObject<Block> Baddeleyite = BLOCKS.register("baddeleyite",Baddeleyite::new);
    public static final RegistryObject<Block> VanadiumTitanoMagnetite = BLOCKS.register("vanadium_titano_magnetite",VanadiumTitanoMagnetite::new);
    public static final RegistryObject<Block> Columbite = BLOCKS.register("columbite",Columbite::new);
    public static final RegistryObject<Block> Coltan = BLOCKS.register("coltan",Coltan::new);
    public static final RegistryObject<Block> Molybdenite = BLOCKS.register("molybdenite",Molybdenite::new);
    public static final RegistryObject<Block> Wolframite = BLOCKS.register("wolframite",Wolframite::new);
    public static final RegistryObject<Block> Scheelite = BLOCKS.register("scheelite",Scheelite::new);
    public static final RegistryObject<Block> DeepPortalToDeep = BLOCKS.register("deep_portal_to_deep", DeepPortalToDeep::new);
    public static final RegistryObject<Block> VeryDeepPortalToVeryDeep = BLOCKS.register("very_deep_portal_to_very_deep", VeryDeepPortalToVeryDeep::new);
    public static final RegistryObject<Block> DeepPortalToOverworld =BLOCKS.register("deep_portal_to_overworld",DeepPortalToOverworld::new);
    public static final RegistryObject<Block> VeryDeepPortalToDeep = BLOCKS.register("very_deep_portal_to_deep", VeryDeepPortalToDeep::new);
    public static final RegistryObject<Block> Xenotime = BLOCKS.register("xenotime", Xenotime::new);
    public static final RegistryObject<Block> Bastnasite = BLOCKS.register("bastnasite", Bastnasite::new);
    public static final RegistryObject<Block> Phosphocerite = BLOCKS.register("phosphocerite", Phosphocerite::new);
    public static final RegistryObject<Block> XenotimeVeryDeep = BLOCKS.register("xenotime_very_deep", XenotimeVeryDeep::new);
    public static final RegistryObject<Block> BastnasiteVeryDeep = BLOCKS.register("bastnasite_very_deep", BastnasiteVeryDeep::new);
    public static final RegistryObject<Block> PhosphoceriteVeryDeep = BLOCKS.register("phosphocerite_very_deep", PhosphoceriteVeryDeep::new);
    public static final RegistryObject<Block> SilverOre = BLOCKS.register("silver_ore", SilverOre::new);
    public static final RegistryObject<Block> GoldOreVeryDeep = BLOCKS.register("gold_ore_very_deep", GoldOreVeryDeep::new);
    public static final RegistryObject<Block> PlatinumOre = BLOCKS.register("platinum_ore", PlatinumOre::new);
    public static final RegistryObject<Block> IridosmineOre = BLOCKS.register("iridosmine_ore", IridosmineOre::new);
    public static final RegistryObject<Block> BlastFurnaceBaseCore = BLOCKS.register("blast_furnace_base_core", BlastFurnaceBaseCore::new);
    public static final RegistryObject<Block> BlastFurnaceBase = BLOCKS.register("blast_furnace_base", com.xzk.tech.block.BlastFurnaceBaseMachine.BlastFurnaceBase::new);
    public static final RegistryObject<Block> BlastFurnaceBaseMultiBlocks = BLOCKS.register("blast_furnace_base_multi_blocks", BlastFurnaceBaseMultiBlocks::new);
    public static final RegistryObject<Block> BlastFurnaceBaseDoors = BLOCKS.register("blast_furnace_base_doors", BlastFurnaceBaseDoors::new);
    public static final RegistryObject<Block> Fe_CBlock = BLOCKS.register("fe_c_block", Fe_CBlock::new);
    public static final RegistryObject<Block> BoilersBase = BLOCKS.register("boilers_base", BoilersBase::new);
    public static final RegistryObject<Block> BoilersBaseMultiBlocks = BLOCKS.register("boilers_base_multi_blocks", BoilersBaseMultiBlocks::new);
    public static final RegistryObject<Block> BoilersBaseCore = BLOCKS.register("boilers_base_core",BoilersBaseCore::new);
    public static final RegistryObject<Block> IronPlateBlock = BLOCKS.register("iron_plate_block",IronPlateBlock::new);
}