package com.xzk.tech.block;

import com.xzk.tech.group.ModGroup;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class ItemRegistry {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS,"tech");
    public static final RegistryObject<Item> Beryl = ITEMS.register("beryl", () -> new BlockItem(BlockRegistry.Beryl.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Spodumene = ITEMS.register("spodumene", () -> new BlockItem(BlockRegistry.Spodumene.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Lepidolite = ITEMS.register("lepidolite", () -> new BlockItem(BlockRegistry.Lepidolite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> BoraxOre = ITEMS.register("borax_ore", () -> new BlockItem(BlockRegistry.BoraxOre.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Priceite = ITEMS.register("priceite", () -> new BlockItem(BlockRegistry.Priceite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> RockSaltOre = ITEMS.register("rock_salt_ore", () -> new BlockItem(BlockRegistry.RockSaltOre.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Magnesite = ITEMS.register("magnesite", () -> new BlockItem(BlockRegistry.Magnesite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Carnallite = ITEMS.register("carnallite", () -> new BlockItem(BlockRegistry.Carnallite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Bauxite = ITEMS.register("bauxite", () -> new BlockItem(BlockRegistry.Bauxite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Apatite = ITEMS.register("apatite", () -> new BlockItem(BlockRegistry.Apatite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> SulfurOre = ITEMS.register("sulfur_ore", () -> new BlockItem(BlockRegistry.SulfurOre.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> CalciumCarbonate = ITEMS.register("calcium_carbonate", () -> new BlockItem(BlockRegistry.CalciumCarbonate.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Chromite = ITEMS.register("chromite", () -> new BlockItem(BlockRegistry.Chromite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Pyrolusite = ITEMS.register("pyrolusite", () -> new BlockItem(BlockRegistry.Pyrolusite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Psilomelane = ITEMS.register("psilomelane", () -> new BlockItem(BlockRegistry.Psilomelane.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Magnetite = ITEMS.register("magnetite", () -> new BlockItem(BlockRegistry.Magnetite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Pentlandite = ITEMS.register("pentlandite", () -> new BlockItem(BlockRegistry.Pentlandite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Chalcocite = ITEMS.register("chalcocite", () -> new BlockItem(BlockRegistry.Chalcocite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Chalcopyrite = ITEMS.register("chalcopyrite", () -> new BlockItem(BlockRegistry.Chalcopyrite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> SphaleriteAndGalena = ITEMS.register("sphalerite_and_galena", () -> new BlockItem(BlockRegistry.SphaleriteAndGalena.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Smithsonite = ITEMS.register("smithsonite", () -> new BlockItem(BlockRegistry.Smithsonite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Arsenopyrite = ITEMS.register("arsenopyrite", () -> new BlockItem(BlockRegistry.Arsenopyrite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Stibnite = ITEMS.register("stibnite", () -> new BlockItem(BlockRegistry.Stibnite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Cassiterite = ITEMS.register("cassiterite", () -> new BlockItem(BlockRegistry.Cassiterite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Pollucite = ITEMS.register("pollucite", () -> new BlockItem(BlockRegistry.Pollucite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Witherite = ITEMS.register("witherite", () -> new BlockItem(BlockRegistry.Witherite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Barite = ITEMS.register("barite", () -> new BlockItem(BlockRegistry.Barite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Cinnabar = ITEMS.register("cinnabar", () -> new BlockItem(BlockRegistry.Cinnabar.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Bismite = ITEMS.register("bismite", () -> new BlockItem(BlockRegistry.Bismite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> DeepStone = ITEMS.register("deep_stone", () -> new BlockItem(BlockRegistry.DeepStone.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> VeryDeepStone = ITEMS.register("very_deep_stone", () -> new BlockItem(BlockRegistry.VeryDeepStone.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> SpodumeneDeep = ITEMS.register("spodumene_deep", () -> new BlockItem(BlockRegistry.SpodumeneDeep.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> PolluciteDeep = ITEMS.register("pollucite_deep", () -> new BlockItem(BlockRegistry.PolluciteDeep.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> LepidoliteDeep = ITEMS.register("lepidolite_deep", () -> new BlockItem(BlockRegistry.LepidoliteDeep.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Rutile = ITEMS.register("rutile", () -> new BlockItem(BlockRegistry.Rutile.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> ZirconProducts = ITEMS.register("zircon_products", () -> new BlockItem(BlockRegistry.ZirconProducts.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Baddeleyite = ITEMS.register("baddeleyite", () -> new BlockItem(BlockRegistry.Baddeleyite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> VanadiumTitanoMagnetite = ITEMS.register("vanadium_titano_magnetite", () -> new BlockItem(BlockRegistry.VanadiumTitanoMagnetite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Columbite = ITEMS.register("columbite", () -> new BlockItem(BlockRegistry.Columbite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Coltan = ITEMS.register("coltan", () -> new BlockItem(BlockRegistry.Coltan.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Molybdenite = ITEMS.register("molybdenite", () -> new BlockItem(BlockRegistry.Molybdenite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Wolframite = ITEMS.register("wolframite", () -> new BlockItem(BlockRegistry.Wolframite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> DeepPortalToDeep = ITEMS.register("deep_portal_to_deep", () -> new BlockItem(BlockRegistry.DeepPortalToDeep.get(), new Item.Properties()));
    public static final RegistryObject<Item> VeryDeepPortalToVeryDeep = ITEMS.register("very_deep_portal_to_very_deep", () -> new BlockItem(BlockRegistry.VeryDeepPortalToVeryDeep.get(), new Item.Properties()));
    public static final RegistryObject<Item> DeepPortalToOverworld = ITEMS.register("deep_portal_to_overworld", () -> new BlockItem(BlockRegistry.DeepPortalToOverworld.get(), new Item.Properties()));
    public static final RegistryObject<Item> VeryDeepPortalToDeep = ITEMS.register("very_deep_portal_to_deep", () -> new BlockItem(BlockRegistry.VeryDeepPortalToDeep.get(), new Item.Properties()));
    public static final RegistryObject<Item> Scheelite = ITEMS.register("scheelite", () -> new BlockItem(BlockRegistry.Scheelite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Xenotime = ITEMS.register("xenotime", () -> new BlockItem(BlockRegistry.Xenotime.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Bastnasite = ITEMS.register("bastnasite", () -> new BlockItem(BlockRegistry.Bastnasite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> Phosphocerite = ITEMS.register("phosphocerite", () -> new BlockItem(BlockRegistry.Phosphocerite.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> XenotimeVeryDeep = ITEMS.register("xenotime_very_deep", () -> new BlockItem(BlockRegistry.XenotimeVeryDeep.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> BastnasiteVeryDeep = ITEMS.register("bastnasite_very_deep", () -> new BlockItem(BlockRegistry.BastnasiteVeryDeep.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> PhosphoceriteVeryDeep = ITEMS.register("phosphocerite_very_deep", () -> new BlockItem(BlockRegistry.PhosphoceriteVeryDeep.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> SilverOre = ITEMS.register("silver_ore", () -> new BlockItem(BlockRegistry.SilverOre.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> GoldOreVeryDeep = ITEMS.register("gold_ore_very_deep", () -> new BlockItem(BlockRegistry.GoldOreVeryDeep.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> PlatinumOre = ITEMS.register("platinum_ore", () -> new BlockItem(BlockRegistry.PlatinumOre.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> IridosmineOre = ITEMS.register("iridosmine_ore", () -> new BlockItem(BlockRegistry.IridosmineOre.get(), new Item.Properties().tab(ModGroup.Ores)));
    public static final RegistryObject<Item> BlastFurnaceBaseCore = ITEMS.register("blast_furnace_base_core", () -> new BlockItem(BlockRegistry.BlastFurnaceBaseCore.get(), new Item.Properties().tab(ModGroup.Machines)));
    public static final RegistryObject<Item> Fe_CBlock = ITEMS.register("fe_c_block", () -> new BlockItem(BlockRegistry.Fe_CBlock.get(), new Item.Properties().tab(ModGroup.BasicElements)));
    public static final RegistryObject<Item> BoilersBaseCore = ITEMS.register("boilers_base_core", () -> new BlockItem(BlockRegistry.BoilersBaseCore.get(), new Item.Properties().tab(ModGroup.Machines)));
    public static final RegistryObject<Item> IronPlateBlock = ITEMS.register("iron_plate_block", () -> new BlockItem(BlockRegistry.IronPlateBlock.get(), new Item.Properties().tab(ModGroup.Machines)));
}
